// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import env from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  firebaseConfig: {
    apiKey: 'AIzaSyCcfmLG2y1ylNQYiFlw2eu_4vRTBFCl7Oo',
    authDomain: 'carpooler-7e16a.firebaseapp.com',
    databaseURL: 'https://carpooler-7e16a.firebaseio.com',
    projectId: 'carpooler-7e16a',
    storageBucket: 'carpooler-7e16a.appspot.com',
    messagingSenderId: '799878032074',
    appId: '1:799878032074:web:24881fb85fa1946c'
  }
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
